#!/bin/bash

if [[ $# = "0" ]]; then
    printf "Error: no argument provided\n"
    exit 0
fi


case $1 in
    "pull")
        $GITGUD_PATH/push_pull_repos.sh pull $2
        ;;
    "push")
        git config --global credential.helper 'cache --timeout=900'
        $GITGUD_PATH/push_pull_repos.sh push $2
        ;;
    "pizza")
        cd $GITGUD_PATH
        python3 pizza_order.py
        ;;
    "help")
        printf "%s\n" "Usage: gitgud [arg]. The available arguments are:"
        printf "\t%s\n" "pull - pull all git repositories in current directory"
        printf "\t%s\n" "push - push all git repositories in current direcotry"
        printf "\t%s\n" "pizza - order pizza"
        printf "\t%s\n" "help - see this help text"
        ;;
    *)
        printf "Error: unrecognized argument. Run 'gitgud help' to see what arguments are available.\n"
        ;;
esac

